### ISSUE TITLE
Mention that --help also works in subcommands, if they're present

### ISSUE THREAD

**Issue by Shnatsel** [pacak/bpaf#1]
First off, thanks for writing this library! I think it strikes a very nice balance between complexity and expressiveness.

I am currently converting [`cargo supply-chain`](https://github.com/rust-secure-code/cargo-supply-chain) from `pico-args` to `bpaf`. I am in a situation where *most* subcommands have the same options, but one does not. This results in a `--help` output that lists no flags at all:

```
Gather author, contributor and publisher data on crates in your dependency graph

Usage: COMMAND

Available options:
    -h, --help   Prints help information

Available commands:
    publishers  List all crates.io publishers in the depedency graph
    crates      List all crates in dependency graph and crates.io publishers for each
    json        Like 'crates', but in JSON and with more fields for each publisher
    update      Download the latest daily dump from crates.io to speed up other commands
```

While technically correct, this is confusing: after all, there are many more options that aren't listed, they're just specific to subcommands.

For reference, `cargo` itself prints `See 'cargo help <command>' for more information on a specific command.` at the end of its help output. I think adding a similar line mentioning that `--help` also works on subcommands would be a significant improvement.

**Comment by Shnatsel** [comment]
For reference, the handwritten help output I've used up until this point can be found [here.](https://github.com/rust-secure-code/cargo-supply-chain/blob/bd8bc42b8ecd6b74f8641cb2f4c6d3bec7e42716/README.md#usage)

**Comment by pacak** [comment]
Did you try using methods on `Info`? Cargo's behavior can be replicated with `footer`. Most of the behavior in the example you listed too - except arguments are going before commands.

https://docs.rs/bpaf/0.2.0/bpaf/struct.Info.html#method.footer

**Comment by Shnatsel** [comment]
Ah, I have missed that! It does indeed serve my use case, and it's a more general approach than what I had in mind. Thanks!
