### ISSUE TITLE
BUG: Broken documentation links in the README.md

### ISSUE THREAD

**Issue by slonik-az** [pacak/bpaf#103]
Documentation links on the `bpaf` landing page in github (`README.md`) refer to version `0.7.0` that does not exist on the https://docs.rs/bpaf/   The latest existing version there is `0.6.1`.

**Comment by pacak** [comment]
Hmmm... I'm getting ready to release a new version soon-ish and want to see how new docs look like remotely. I guess README can still point at 0.6.1... Will push something to fix it.

**Comment by pacak** [comment]
Should be fixed now, thank you for the report. I need to think a bit more to how to do this kind of stuff in the future.
