### ISSUE TITLE
OptionParser deriving Clone

### ISSUE THREAD

**Issue by imsamuka** [pacak/bpaf#116]
Could `OptionParser` derive `Clone`?

I use bpaf to simulate a REPL of subcommands. I don't know if it affects performance that much, but it's quite wasteful to recreate the parser from scratch every time, a user inputs something, specially since there's a lot of subcommands...

**Comment by pacak** [comment]
`OptionParser::run_inner` takes a reference so you can reuse the same `OptionParser` over and over again.

**Comment by pacak** [comment]
What kind of a project are you trying to implement?

**Comment by imsamuka** [comment]
Oh i see, in earlier versions both `run` and `run_inner` took ownership, and I had to clone it. That's a way better solution

> What kind of project are you trying to implement?

It's a deamon, and a helper program where you can input the various commands to interact with it. `bpaf` have been a very good fit since the beginning.
