### ISSUE TITLE
Parsing parameters from environment variables

### ISSUE THREAD

**Issue by mneumann** [pacak/bpaf#12]
Would be nice to add some helper method that would simplify to parse a value out of an environment variable.

Currently what I am doing is:

```
.fallback_with(|| std::env::var("ABC"))
```

This works pretty well, though it's not as nice as e.g. strutopts `env="..."` annotation, which also display the environment variable name in the help message and also the value.

**Comment by mneumann** [comment]
I am thinking of something similar to `long` or `short`, but named `env("ABC")`

**Comment by pacak** [comment]
I need to think about how it will interact with other planned features such as completion info generation. Your workaround doesn't look terrible, you can make it a bit shorter by defining a macro so code you type looks something like `fallback_with(env!("ABC"))`.

What kind of parameters are you passing with both command line arguments and env variables?

**Comment by mneumann** [comment]
mainly credentials, but also thinks like API endpoints, where I want to be able to source them from either an env variable or a command line option.

`fallback_with` has the downside that there is no way to generate a proper help message (like structopt does).

**Comment by pacak** [comment]
Okay, places where values from a command line can go and a few possible interactions

- named arguments such as `-f foo.rs`
- flags and  switches: `ls -l`
- positional arguments, such as `rustc foo.rs`
- commands, such as `cargo check`

For named arguments fallback to an env variable is easy to add and it sort of makes sense, it would look something like this:
```rust
let file = short('f').long("file").env("INPUT_FILE")
               .help("Input file to use").argument_os("FILE").map(PathBuf::from);
```
 Should bpaf allow adding a named argument that doesn't have a name, should this be valid? It doesn't make much sense to me but maybe I'm missing something obvious.
 ```rust
let file = env("INPUT_FILE").help("Input file to use").argument_os("FILE").map(PathBuf::from);
 ```

Flags and switches. Similar to named, and environment variable being present could map to flag present - most (all?) apps ignore value of `NO_COLOR` env variable, just use the fact it is there.

Positional and commands. I'm not sure if env variables can be supported here without making things more confusing or adding strange interactions.

Thoughts? Would supporting env variables for named arguments and flags be enough to cover your use cases?

**Comment by pacak** [comment]
https://github.com/pacak/bpaf/tree/exp-env - experimental implementation here

**Comment by pacak** [comment]
published 0.4.8, `env` should be available.

**Comment by mneumann** [comment]
@pacak I think it makes sense to allow `env()` without a correspondent named argument. Let's say, I want to write a program that uses env `RUST_LOG`. Where do I find this information? It's not shown in the `--help` output. But with `bpaf`, it would appear in the help output.

**Comment by pacak** [comment]
> I think it makes sense to allow `env()` without a correspondent named argument

Are there any reasons you can't also give it a name? So `env("RUST_LOG").long("rust-log")`? It is possible to render without the name as well but this create a few more corner cases to consider in the help rendering and other places.

**Comment by mneumann** [comment]
It's fine for me to require a name.
