### ISSUE TITLE
Question: How can I parse a positional argument where some variants of that argument require a second positional argument?

### ISSUE THREAD

**Issue by alex-psl** [pacak/bpaf#13]
First of all, thanks for `bpaf`. Great tool, and I love its light footprint.

I'm trying to parse a structure that more or less looks like this: 

```
enum Mode {
  Foo,
  Bar { baz: String }
}
```

Ideally, `app foo`  parses to `Mode::Foo` and `app bar quux` parses to `Mode::Bar { baz: "quux" }`. 

I've tried combining positional parsers and even implementing my own, but I'm pretty sure I'm barking up the wrong tree. Is there a relatively simple, canonical way of doing this with `bpaf`?

Thanks!

**Comment by pacak** [comment]
Positional with a special meaning that changes the meaning of subsequent parsers is usually a `command` and you combine them with `foo.or_else(bar)` or `construct!([foo, bar])`.

https://github.com/pacak/bpaf/blob/master/examples/git.rs
https://github.com/pacak/bpaf/blob/master/examples/derive_rudo.rs

**Comment by alex-psl** [comment]
This worked perfectly, thank you!
