### ISSUE TITLE
manpages: wrong package metadata

### ISSUE THREAD

**Issue by ysndr** [pacak/bpaf#139]
The generated manpages end with the following lines (despite `package.{authores, homepage, repository}` set in `Cargo.toml`:

```
AUTHORS
       Michael Baykov <manpacket@gmail.com>

REPORTING BUGS
       https://github.com/pacak/bpaf
```

**Comment by pacak** [comment]
I guess that's me using `env!` inside... `src/manpage.rs`, my bad. If you are making a change for !138 - can you include this as well? Exposing url and authors should do the trick. I'll make a release shortly after.

**Comment by pacak** [comment]
Thank you for testing and fixing the problems. Is everything else look fine? If so - I'll publish a new version in an hour or so.

**Comment by ysndr** [comment]
Don't think there is anything else too problematic.
I think the subcommand structure should be flatter than it is, we only got two levels at our disposal after all and we have to show group `Header > command group labels > commands > arg group labels`

I started something in https://github.com/pacak/bpaf/pull/142

which would end up as 

```
# OPTIONS
	## Option Group
	--arg
		Description

# SUBCOMMANDS
	## Command Group
    ## command subcommand, s
		Description
		Paragraph
		
		**arg group labels**
		--arg
			Description
```

the PR above goes some way inthat direction but isn't all the way there.

**Comment by pacak** [comment]
> the PR above goes some way inthat direction but isn't all the way there.

I see, will take a look. And will update the tests for man pages to make them easier to verify

**Comment by pacak** [comment]
Pushed `rc-0.7.8`, does this look better to you?

**Comment by pacak** [comment]
Using `git` as a reference sounds like a great idea, will see what I can do, probably tomorrow.

**Comment by ysndr** [comment]
mind git focuses on separating (1st level) subcommands into separate files eg `man git-remote`


Snip from `man git`:

```
HIGH-LEVEL COMMANDS (PORCELAIN)
       We separate the porcelain commands into the main commands and some ancillary user utilities.

   Main porcelain commands
       git-add(1)
           Add file contents to the index.

       git-am(1)
           Apply a series of patches from a mailbox

```


notably they have two nested groups of subcommands (`# HIGH-LEVEL COMMANDS (PORCELAIN)` and `## Main porcelain commands`, `## Interacting with Others`, ...)

**Comment by pacak** [comment]
Sorry for the delay, I'm going though man page formats, generation and related tools, there's  50 years worth of history to them :)

A quick question - how are you using/planning to use manpages?

**Comment by ysndr** [comment]
> I'm going though man page formats, generation and related tools, there's 50 years worth of history to them

Sounds.. fun (:

Planning to use manpages as second level documentation

1st level: --help / Usage (User knows what the command does in general but needs help with the flags, arguments)
2nd level: man myprog-cmd / learn what a command is for, how it is intended to be used what effects it will have etc. 
3rd level: external documentation

each higher levels should optimally be a superset of the lower ones.

Clearly the manpages don't need to contain the entire documentation but the more command specific documentation can be put in the manpage the more of the final docs can be generated from a single place

**Comment by pacak** [comment]
> 3rd level: external documentation
> each higher levels should optimally be a superset of the lower ones.

Okay, so it's not just me :)

**Comment by ysndr** [comment]
Maybe https://timewarrior.net/docs/ is  good example

I'd expect everything under ## Command Reference to be generated from manpages (which it seems to be anyway) but discuss patterns and concepts separately as tutorials etc.. (https://timewarrior.net/docs/corrections/)

**Comment by pacak** [comment]
This bug is fixed, more changes will go into semantic crate
