### ISSUE TITLE
`strict` does not work with positionals

### ISSUE THREAD

**Issue by ysndr** [pacak/bpaf#153]
Maybe i misunderstand what strict is doing, but i expected it to collect excess arguments after `--`.

Consider an argument struct like this:

```

#[derive(Bpaf, Debug)]
struct Args {
	#[bpaf(long)]
	flag: bool,

	#[bpaf(positional)]
	pos: Option<String>,

	#[bpaf(external)]
	strict: Vec<String>
}

fn strict() -> impl Parser<Vec<String>> {
	positional("strict").strict().many()
}

fn main() {
    let a = args().run();
    dbg!(&a);
}
```

The usage is

```
Usage: [--flag] [<ARG>] -- <strict>...
```

yet 

```
prog --flag -- hello
```

gets parsed as 

```
Args {
	flag: true,
	pos: Some("hello"),
	strict: [],
}
```

This even breaks if pos is not a positional:

```
Args {
    flag: true,
    pos: "--help",
    strict: [],
}
```

**Comment by pacak** [comment]
I think this works as expected: `--` is usually used in shell to tell that there's no more arguments past this point, only positional ones. What `strict` does is changes positional parser to accept only. It does not affect how other parsers consume it: `hello` in your example is still positional so `pos` will happily consume it. Documentation might be not very good at explaining that though.

**Comment by ysndr** [comment]
I see the explanation makes sense.
How would you implement something like 

```
[--flag] [<ARG>] -- <strict>...
https://git-scm.com/docs/git-diff
Usage: cabal run [TARGET] [FLAGS] [-- EXECUTABLE_FLAGS]

```

then?
Using some custom parsing with any perhaps?

I'd expect that the parser is switched to accept only positional but then those positionals end up in that parser not an unrelated one
I expected this to work more like [claps last Attribute](https://docs.rs/clap/latest/clap/builder/struct.Arg.html#method.last)

**Comment by pacak** [comment]
I'd implement it by not having optional positional elements in the mix. For example in your case making `pos` required mostly avoids the problem - user needs to specify it either way. 

Then there's https://docs.rs/bpaf/0.7.7/bpaf/trait.Parser.html#method.anywhere that might do what you want if you parse your `strict` field before `pos` field:

```rust
#[derive(Bpaf, Debug)]
struct Args {
	#[bpaf(long)]
	flag: bool,

	#[bpaf(external)]
	strict: Vec<String>

	#[bpaf(positional)]
	pos: Option<String>,
}

fn strict() -> impl Parser<Vec<String>> {
	positional("strict").strict().many().anywhere()
}

fn main() {
    let a = args().run();
    dbg!(&a);
}
```

But that might be confusing for your users.

**Comment by ysndr** [comment]
Yes the usage is rather confusing for that one (`[--flag] -- <strict>... [<ARG>]`).
IMO the usage string produced by my inital solution looks right, it just does not parse like that.

I think i won't be able to to have that positional argument required though. There should be a way to just say "stop parsing _right_ of this token".
It's bothers me a bit that other parsers can take arguments from behind the `--`

**Comment by pacak** [comment]
You can work around the usage string by having two copies of `strict` field, one that would parse and one that would display. something like this:

```
#[derive(Bpaf, Debug)]
struct Args {
	#[bpaf(long)]
	flag: bool,

	#[bpaf(external)]
	real_strict: Vec<String>

	#[bpaf(positional)]
	pos: Option<String>,

	#[bpaf(positional)]
	strict: Vec<String>,
}

fn strict() -> impl Parser<Vec<String>> {
	positional("strict").strict().many().anywhere().hide()
}

fn main() {
    let a = args().run();
    dbg!(&a);
}
```

> I think i won't be able to to have that positional argument required though. There should be a way to just say "stop parsing right of this token".

Can you explain a bit what kind of interface you are trying to build?

> It's bothers me a bit that other parsers can take arguments from behind the `--`

That's how `--` behaves in most application though. Here's what `ls` does for example:

```console
% ls -- before
before
% ls before
before
```

**Comment by ysndr** [comment]
My use case is closer to 

```
cabal run [TARGET] [-- EXECUTABLE_FLAGS]
```

I want to run a sub process and pass excess arguments to it
Therefore it is important that I can tell an end of my host commands arguments and extra arguments that are being passed to that executable.

You can optionally select a target, or it falls back to some default.
I agree that `--` is used for something closer to what strict does now, i.e. allow `ls`ing a directory called `-la` - but that does not explain why a `strict` marged positional does not contain the elements following the `--`
I think there is some default handling of `--` already though.
Al least `any().many()` does not contain `--` and an empty `req_flag("")` _also_ does not parse `--`.

**Comment by ysndr** [comment]
The workaround with the derive syntax is a bit annoying considering i have many ~10 commands if not more that require this, and no way to generically define these structs ;)

**Comment by pacak** [comment]
There's no way to generically define them with derive (yet), but I'm not sure you need it:

```rust
struct TargetAndArgs {
    target: Option<String>,
    args: Vec<OsString>,
}

fn target_and_args() -> impl Parser<TargetAndArgs> {
    let target = positional("target").optional();
    let real_args = positional("args").strict().many().anywhere().hide();
    let fake_args = positional("args").many();
    construct!(real_args, target, fake_args).map(|(args, target, _fake_args)| TargetAndArgs { target, args })
}
```

Then just make `TargetAndArgs` a field in your other commands and use it via `external`.

**Comment by ysndr** [comment]
Another issue with "optional" positionals (dont know if thats its own issue, seems related though)

```
#[derive(Bpaf, Debug)]
struct Args {
	#[bpaf(positional, optional)]
	pos: Option<String>,
	#[bpaf(long)]
	flag: bool,
}
```

```
$ prog --flag
Expected an argument, got --flag
```

To your credit, if run with `--help` it does create a `usage Bug` error

**Comment by pacak** [comment]
> Another issue with "optional" positionals (dont know if thats its own issue, seems related though)

That's about any positional items, you need to parse them after any flags. Not specific to my parser and is required to deal with ambiguous cases.

> To your credit, if run with `--help` it does create a usage `Bug` error

There's also this to catch this problem during tests: https://docs.rs/bpaf/0.7.7/bpaf/struct.OptionParser.html#method.check_invariants

**Comment by ysndr** [comment]
> Not specific to my parser and is required to deal with ambiguous cases.
I know, just tried things around and stumbled over that - in hind sight that makes sense.

> There's no way to generically define them with derive (yet), but I'm not sure you need it:

Well target is the generic part, all commands parse a target but with light generic alteration.
I dont particularly like mixing my argument with "their" argument, but that's the cleanest solution i've seen so far

**Comment by pacak** [comment]
I guess this and type aliases to work around not being able to have generic fields in struct. Or using `construct` macro...
```rust
struct TargetAndArgs<T> {
    target: Option<T>,
    args: Vec<OsString>,
}

fn target_and_args<T>(target: impl Parser<T>) -> impl Parser<TargetAndArgs<T>> {
    let target = target.optional();
    let real_args = positional("args").strict().many().anywhere().hide();
    let fake_args = positional("args").many();
    construct!(real_args, target, fake_args).map(|(args, target, _fake_args)| TargetAndArgs { target, args })
}
```

**Comment by ysndr** [comment]
Or with a parseable generic :P

```
fn target_and_args<T: Parseable>() -> impl Parser<TargetAndArgs<T>> {
    let target = T::parser().optional();
    let real_args = positional("args").strict().many().anywhere().hide();
    let fake_args = positional("args").many();
    construct!(real_args, target, fake_args).map(|(args, target, _fake_args)| TargetAndArgs { target, args })
}
```

**Comment by ysndr** [comment]
So, this seems to works somewhat with an explicit `--` :)

it also works without `--` if the `optional` is given, but not if the optional is substituted with a default:

```
prog --flag pos -- --other other_pos ✔
prog --flag pos --other other_pos ✔
prog --flag --other other_pos ❌
```

**Comment by pacak** [comment]
Hmm... `fake_args` should be `strict` too.

**Comment by ysndr** [comment]
oh i have it since made fake args an `any`:

```rust
let real_args = bpaf::positional("args")
            .strict()
            .many()
            .anywhere()
            .hide()
            .fallback(Vec::new());

let inner = T::parse();
let fake_args = bpaf::any("args")
    .guard(
        |m: &String| !["--help", "-h"].contains(&m.as_str()),
        "asdas",
    )
    .many();
```

as a possitionl it didnt accept flags and with `strict` it requires `--`

**Comment by pacak** [comment]
The idea for `fake_args` is not to accept anything at all but to serve as something that would be used to display in usage string and help.

`fallback(Vec::new())` for `many()` field is not doing anything - `many()` never fails in a way that can trigger `fallback()`.

Something like this:
```rust
let real_args = bpaf::positional("args")
            .strict()
            .many()
            .anywhere()
            .hide();

let inner = T::parse();
let fake_args = bpaf::positional("args").strict().many();
```

**Comment by ysndr** [comment]
As I mention above 

>  with strict it requires `--`

So I do collect some `fake_args` as `any` and combine the result with `real_args` to make the `--` optional

> ```
> prog --flag pos --other other_pos ✔
> ```

However, that way it requires the optional argument again

> ```
> prog --flag --other other_pos ❌
> ```

**Comment by pacak** [comment]
> So I do collect some fake_args as any and combine the result with real_args to make the -- optional

Hmm... Basically "parse flags by the outer program including optional positional target and then pass everything unused to the child program with `--` being default"?

You could parse everything as usual, make `target` parser to be optional using `optional` and `ParseOptional::catch` and then collect everything else (except for `-h` or `--help`) with `any` and pass that.

**Comment by ysndr** [comment]
Aha, there we go - i think...

I ended up with

```
let real_args = bpaf::positional("args")
            .strict()
            .many()
            .anywhere()
            .hide()
            .fallback(Vec::new());

let inner = T::parse().optional().catch()；
let fake_args = bpaf::any("args")
    .guard(
        |m: &String| !["--help", "-h"].contains(&m.as_str()),
        "asdas",
    )
    .many();

 construct!(real_args, inner, fake_args).map(|(mut real_args, inner,  mut fake_args)| {
            real_args.append(&mut fake_args);

            InnerAndArgs { inner, real_args }
        })

```

which seems to do what i want and allows forcing parsing behind `--`.

Thank you so much for assisting!
Though, my confusion with `strict` and that it should collect the elements after `--` by default still stands, having to fall back to this wrapping is a bit inconvenient.

**Comment by pacak** [comment]
You don't need this fallback at `real_args`: `.fallback(Vec::new());`

**Comment by ysndr** [comment]
seems like i do, since without 

```
prog pos --unknown
```

doesn't parse

**Comment by pacak** [comment]
Interesting. I'll take a look later, looks like a bug.
