### ISSUE TITLE
Completions suggest unparseable commands

### ISSUE THREAD

**Issue by ysndr** [pacak/bpaf#162]
.. or some issue with groups i guess.

I have a parser that should switch between sub commands of different groups:

```

#[derive(Bpaf)]
enum Groups {
    GroupA(#[bpaf(external(group_a), group_help("Group A"))] GroupA),

    GroupBWrapper {
        #[bpaf(long, short)]
        shared: Option<String>,

        #[bpaf(external, group_help("Group B"))]
        group_b: GroupB,
    },
}

#[derive(Bpaf, Clone)]
enum GroupA {
    #[bpaf(command)]
    One,
    #[bpaf(command)]
    Two,
    #[bpaf(command)]
    Three,
}

#[derive(Bpaf, Clone)]

enum GroupB {
    #[bpaf(command)]
    Alpha,
    #[bpaf(command)]
    Beta,
    #[bpaf(command)]
    Gamma,
}

fn main() {
    let _ = groups().to_options().run();
}
```

Some groups may contain arguments that are supposed to come _before_ the commands but are only valid for said commands. That is in this case, with the `--shared` flag, only `GroupB` commands shall be valid.

The usage represents that somewhat:

```
Usage: (COMMAND ... | [-s ARG] COMMAND ...)

Available options:
    -s, --shared <ARG>
    -h, --help          Prints help information

Available commands:
  Group A
    one
    two
    three

  Group B
    alpha
    beta
    gamma
```

Yet, `--shared` is not under a `Group B` category.

Now when I try to complete sub commands I do get all subcommands and `--shared` (as expected)

```
$ prog <tab>
--shared <ARG>  beta            one             two                           
alpha           gamma           three 
```

However, once i complete with `--shared` the completion options still contain elements from `GroupA`.

```
$prog --shared bla <tab>
alpha  beta   gamma  one    three  two 
```

And in fact, `GroupA` commands are _not_ accepted:

```
$ prog --shared asd one 
Expected COMMAND ..., pass --help for usage information
```

- I'd expect `--shared` to be grouped under a `Group A` category
- I'd Expect some way to change `COMMMAND` to either the concrete values (see git's usage maybe) or change the placeholder per group
- with `--shared` only the completions for `GroupA` are valid, `GroupB` variants should not be suggested

**Comment by ysndr** [comment]
Thanks!
haven't had the time to look at it, busy times atm will do as soon as i can get to it

**Comment by pacak** [comment]
No worries, busy times are totally understandable, take your time.
