### ISSUE TITLE
Fallback is not documented in usage

### ISSUE THREAD

**Issue by teohhanhui** [pacak/bpaf#167]
Following the example here: https://github.com/pacak/bpaf/blob/4f64f34b2370b30b3ec98872f5ba1a936a6a9e81/examples/multiple_fallback.rs

If I have something like:

```rust
use bpaf::Bpaf;
use once_cell::sync::Lazy;

pub static CONFIG: Lazy<Config> = Lazy::new(|| Config {
    http_port: 3000,
});

#[derive(Clone, Debug, Bpaf)]
#[bpaf(options, version)]
pub struct Config {
    /// Listening port of HTTP server
    #[bpaf(long, env("APP_HTTP_PORT"), fallback(CONFIG.http_port))]
    pub http_port: u16,
}
```

Expected:

```
        --http-port <ARG>                [env:APP_HTTP_PORT: N/A]
                                         Listening port of HTTP server
                                         [default: 3000]
```

Actual:

```
        --http-port <ARG>                [env:APP_HTTP_PORT: N/A]
                                         Listening port of HTTP server
```

**Comment by pacak** [comment]
This feature was requested a few times and I'm still thinking about the best way of implementing this. At the moment `fallback` imposes no restrictions on the argument type. To display the default value I can either use `Display` or `Debug`. `Display` means no fallback for `PathBuf` since they don't have `Display`, `Debug` means newtyped values can look strange - `Distance(30.0)` instead of `30.0` for `struct Distance(f64)`...

**Comment by teohhanhui** [comment]
Or let the user (optionally) override the item to use for `Display`, so they could easily call `.display()`

**Comment by pacak** [comment]
Like this?
```rust
#[derive(Clone, Debug, Bpaf)]
#[bpaf(options, version)]
pub struct Config {
    /// Listening port of HTTP server
    #[bpaf(long, env("APP_HTTP_PORT"), fallback(CONFIG.http_port), display_fallback)]
    pub http_port: u16,
}
```

This or `debug_fallback`... Yea, this might work.

> Of course, types that don't implement Display should still be allowed to be used for fallback, but just can't be printed.

Unfortunately this is not Haskell, derive macro can't tell if something implements some trait or not...

**Comment by pacak** [comment]
> What about using sigils like tracing does?

This works for derive macro but not for combinatoric API and I'm trying to keep those two in sync.
