### ISSUE TITLE
many + env = problem

### ISSUE THREAD

**Issue by pacak** [pacak/bpaf#169]
```rust
#[test]
fn many_env() {
    std::env::set_var("USER", "top s3cr3t");
    let parser = short('v')
        .env("USER")
        .argument::<String>("USER")
        .many()
        .to_options();
    let r = parser.run_inner(Args::from(&[])).unwrap();
    todo!("{:?}", r);
}
```

**Comment by pacak** [comment]
Actually this matches documented behavior of many :thinking:

**Comment by teohhanhui** [comment]
Personally, I would not expect an env variable with a value containing whitespace to be treated as multiple arguments... That would violate the principle of least surprise.

**Comment by pacak** [comment]
> Personally, I would not expect an env variable with a value containing whitespace to be treated as multiple arguments... 

It is not treated as multiple variables, `many` runs inner parser multiple times for as long as it consumes something. In current version it will try to run it, will see that it consumed nothing and will discard the results. To split the values inside you'd use `parse` on the inner parser as shown in https://github.com/pacak/bpaf/discussions/168

I'm just wondering what is the right behavior should be. I can opt for also taking the first result in a non consuming case - works with `env` but also changes the result for `switch`/`flag` style parsers. Anything with fallback really.

> That would violate the principle of least surprise.

`PATH` env variable kind of follows this model, but values are separated with `:` instead of space.

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
```

**Comment by teohhanhui** [comment]
> PATH env variable kind of follows this model, but values are separated with : instead of space.

Yes, but that's a special case of the semantics being defined.

If `bpaf` supports specifying a delimiter, I think it'd make sense for it to also apply to the env var (same behaviour like `clap`). No surprises in that case.

As it stands, I'd expect a `Vec` with a single element, because whitespace is not defined as a separator for env vars, generally speaking, unlike CLI args.

**Comment by pacak** [comment]
> As it stands, I'd expect a `Vec` with a single element

Makes sense. I guess I'll update the definition of `many` and will release it as part of 0.8 version
