### ISSUE TITLE
Unable to derive `positional::<bool>` fields

### ISSUE THREAD

**Issue by ysndr** [pacak/bpaf#171]
I want to create a positional that can take boolean values, i.e. literally `true`, and `false`, no fancy parsing necessary.

I started off with this to parse a number in a related command:

```rust
#[derive(Bpaf)]
struct Args {
    #[bpaf(positional("a number"))]
    argument: u32
}
```

changing the `u32` to bool however does not seem to be possible

```rust
#[derive(Bpaf)]
struct Args {
    #[bpaf(positional("a bool"))]
    argument: bool
}
```

results in a compiler error

```
error: Can't derive consumer for unnamed boolean field
  --> crates/---/src/main.rs:71:15
   |
71 |     argument: bool
   |               ^^^^
```

approaches of setting a different parser similarly failed.

```rust
#[bpaf(positional("a bool"), parser(FromStr:from_str)]
#[bpaf(positional("a bool"), parser(bool::parse)]
```

the only thing i found to work is to manually create a parser for the field which is a bit unhandy and inconsistent:

```rust
#[derive(Bpaf)]
struct Args {
    #[bpaf(external(parse_bool)]
    argument: bool
}

fn parse_bool() -> impl Parser<bool> {
	positional("a bool")
}
```

**Comment by pacak** [comment]
This is somewhat intentional. When designing custom handling of field shapes (Option, Vec, bool) I though if anyone will want to parse booleans using literally what you wrote and my conclusion was that nobody would, I guess I was wrong :)

Will make a change to allow this to happen today/tomorrow. Can you explain a bit about your design decisions for this kind of argument?

**Comment by ysndr** [comment]
> Can you explain a bit about your design decisions for this kind of argument?

sure, I'm creating a config file interface which has a flag `--setBool <key> <value>` (where key and value are positionals to somewhat model multi value flags but that's a separate issue)

since i know the type of the value beforehand using this interface, I wanted to leverage bpaf's parsing for consistency (i also have `--serNumber` and `--setString`)

**Comment by pacak** [comment]
And onto fixing this ticket.

https://github.com/RustMagazine/rustmagazine/pull/64 - would appreciate some proof reading btw :)
