### ISSUE TITLE
Is there any a way to make `./app --help` the default behavior when there's no argument passed?

### ISSUE THREAD

**Issue by ghost** [pacak/bpaf#218]
Hi :smiley: ! Thanks for making/maintaining this library.

I've been looking for this in the doc, but sadly I couldn't find it or missed it somewhere (most likely).

I wonder if we could invoke the program without arguments and let it show us the help message by default, the same if you pass `--help` to the program. For reference, please see Haskell's [optparse-applicative](https://hackage.haskell.org/package/optparse-applicative-0.18.1.0/docs/Options-Applicative.html#v:showHelpOnEmpty) package with `showHelpOnEmpty` preference enabled.

This is what I have in mind:
```rust
    // top-level options parser
    construct!([tui_cmd, install_cmd])
        .to_options()
        .show_help_on_empty()
        .version("v0.1.0")
        .run()
```

Output example:

```
$ ./app
Usage: COMMAND ...

Available options:
    -h, --help     Prints help information
    -V, --version  Prints version information

Available commands:
    tui      Show TUI interface
    install  Install
```

Thanks!

**Comment by pacak** [comment]
> Thanks for making/maintaining this library.

Thank you for the kind words :)

> I wonder if we could invoke the program without arguments and let it show us the help message by default, the same if you pass `--help` to the program.

Not in the current version, but it might change in the future given enough demand. For now you can do something like this to achieve the same results:

https://github.com/pacak/bpaf/discussions/186
