### ISSUE TITLE
`bpaf-derive 0.5.0` seems stricter

### ISSUE THREAD

**Issue by scottlamb** [pacak/bpaf#223]
The changelog says that bpaf-derive 0.5.0 "should be faster to compile and a bit more flexible with respect to what is accepted", so I'm guessing it's an accident that the following no longer compiles:

```rust
    /// Sets the given db::auth::SessionFlags.
    ///
    /// default: `http-only,secure,same-site,same-site-strict`.
    #[bpaf(
        argument::<String>("FLAGS"),
        fallback_with(|| Ok::<_, std::convert::Infallible>("http-only,secure,same-site,same-site-strict".to_owned())),
        parse(parse_flags),
    )]
    session_flags: Vec<SessionFlag>,
```

To make that compile I had to make two changes:

* remove the lambda in favor of a function
* remove the trailing comma after the last option `parse(parse_flags)`

as in the following commit: https://github.com/scottlamb/moonfire-nvr/commit/4cbaf178b0ff8f2064650404d0b1a32182fe3698

**Comment by pacak** [comment]
Unintentional side effects of me rewriting most of it, will try to fix both and add tests.
