### ISSUE TITLE
Misaligned help test on arguments accepting a value

### ISSUE THREAD

**Issue by Shnatsel** [pacak/bpaf#3]
Example:

```
The stupid content tracker

Usage: --cache-max-age AGE

Available options:
                               Does stuff
        --cache-max-age <AGE>

    -h, --help                 Prints help information

```
Note that "does stuff" is above the argument. 

Can be reproduced with:
```rust
use bpaf::*;

#[allow(dead_code)]
#[derive(Debug, Clone)]
enum Opt {
    Repro {
        cache_max_age: String,
    }
}

fn main() {
    let cache_max_age = long("cache-max-age")
        .argument("AGE")
        .help("Does stuff");
    let repro_cmd = construct!(Opt::Repro {
        cache_max_age
    });

    let opt = Info::default()
        .descr("The stupid content tracker")
        .for_parser(repro_cmd)
        .run();

    println!("{:?}", opt);
}
```

Other tools tend to place the description either on the same line (e.g. `cargo`) or on the line *after* the argument (e.g. `ripgrep`).

**Comment by pacak** [comment]
I thought it might be confusing. There's two different `help`. One is for attaching a help message to a field and one is to attaching  a shorter description to a group of fields which you are using.

https://docs.rs/bpaf/0.2.1/bpaf/params/struct.Named.html#method.help
https://docs.rs/bpaf/0.2.1/bpaf/struct.Parser.html#method.help

this attaches "Does stuff" to a group of parsers which currently consists only of a single field. It's more useful when you have several related fields constructed into a single subparser, see here for a better example: https://github.com/pacak/bpaf/blob/master/examples/rectangle.rs

```rust
    let cache_max_age = long("cache-max-age")
        .argument("AGE")
        .help("Does stuff");
    let repro_cmd = construct!(Opt::Repro {
        cache_max_age
    });
```

This attached "Does stuff" to the field itself.
```rust
    let cache_max_age = long("cache-max-age")
        .help("Does stuff");
        .argument("AGE")
    let repro_cmd = construct!(Opt::Repro {
        cache_max_age
    });
```

**Comment by pacak** [comment]
I guess I should rename renaming group `help` into `group_help`...

**Comment by pacak** [comment]
FWIW pushed 0.3.0

**Comment by Shnatsel** [comment]
Thanks for addressing this so quickly!

Just so you know, I have no more outstanding issues with `bpaf` and am very happy with the library!

I've opened the PR for migrating `cargo supply-chain` to `bpaf`: https://github.com/rust-secure-code/cargo-supply-chain/pull/73
