### ISSUE TITLE
Bad error message for a command that expects a positional argument

### ISSUE THREAD

**Issue by d86leader** [pacak/bpaf#30]
Exapmple code:
```rust
use bpaf::Parser;

#[derive(Debug, Clone)]
enum Opts {
    Opt { arg: String },
    Noopt,
}

fn main() {
    let command = bpaf::positional("NAME")
        .to_options()
        .descr("descr for command")
        .command("command")
        .help("help for command")
        .map(|arg| Opts::Opt{ arg });

    let noopt = bpaf::pure(Opts::Noopt);
    let run = bpaf::construct!([noopt]);

    let opts = bpaf::construct!([command, run])
        .to_options()
        .descr("top level descr")
        .run();

    match opts {
        Opts::Opt {arg} => println!("Opt {}", arg),
        Opts::Noopt => println!("Noopt"),
    }
}
```

Example invokation:
```
> ./target/debug/bpaf-test 
Noopt
> ./target/debug/bpaf-test command foo
Opt foo
> ./target/debug/bpaf-test command
command is not expected in this context
>
```

"not expected in this context" is a confusing error message, since that command kind of is expected in this context. I think it should rather say something like "eof not expected in this context" or in the best case "expecting a positional argument NAME following 'command'"

**Comment by d86leader** [comment]
Also can I use this space to complain bit how I still don't understand how `pure` works with other parsers? =)
Granted I still haven't read the docs and am working off my knowledge of haskell's optparse-applicative and the examples in the readme, which is a great point in favour of this library (=

**Comment by pacak** [comment]
Great example. What is happening here is first parser fails due to missing positional argument, it then restores the consumed `"command"` and tries to parse the second alternative which succeeds and cleanup finds unconsumed "command" and this fails.

This behavior only makes sense if we want to parse several commands with the same name which would be strange. Will fix.

FWIW 
```diff
    -let noopt = bpaf::pure(Opts::Noopt);
    -let run = bpaf::construct!([noopt]);
    +let run = bpaf::pure(Opts::Noopt);
```

> Granted I still haven't read the docs

new version comes with new docs :)
