### ISSUE TITLE
`ShellComp::File` not working as expected on bash

### ISSUE THREAD

**Issue by ozwaldorf** [pacak/bpaf#371]
Installing completions for [lutgen fe4450](https://github.com/ozwaldorf/lutgen-rs/tree/fe44502951deb4462d568431993257525ed41272) which uses the file mask to eliminate non images:
```bash
*.avif|*.bmp|*.dds|*.exr|*.ff|*.gif|*.hdr|*.ico|*.jpg|*.jpeg|*.png|*.pnm|*.qoi|*.tga|*.tiff|*.webp
```

fails to work as expected on bash (hitting tab after `some`):
![image](https://github.com/user-attachments/assets/0d43c39e-b945-462e-9d8c-0010a5b31a33)

compared to the correct suggestion by zsh:
![image](https://github.com/user-attachments/assets/06c3e766-4b99-415d-a40e-3d5c7808853f)

---

If needed, I can add a standalone example to reproduce the issue

**Comment by pacak** [comment]
I've seen your code, will try to reproduce it myself. Let's see what I can do about bash not cooperating :)

**Comment by ozwaldorf** [comment]
Doing some more digging, even just using `ShellComp::File { mask: None }` ignores whatever prefix the user typed as well, and only suggests things in the current directory

bash only showing current dir:
![image](https://github.com/user-attachments/assets/6d67c690-3ef4-4b5e-b7e6-90e6cabe815f)

vs zsh working as expected:
![image](https://github.com/user-attachments/assets/7d1cebb7-9795-4283-9759-d0853ddfa374)

**Comment by pacak** [comment]
Hopefully will have a chance to look at it today. I have a general idea of what is going wrong, just need to look up the docs and change it to generate correctly escaped stuff.

**Comment by pacak** [comment]
after some experiments managed to produce this manually and it seem to work.
Looks like key part for `_filedir` is having first two lines - local and initialization. So emitting those in addition to `_filedir` for bash should do the trick. Will try to write some of that tomorrow-ish.

```
_de()
{
   local cur prev words cword
   _init_completion || return
  _filedir '@(md|toml)'
}
complete -F _de de

_dr()
{
   local cur prev words cword
   _init_completion || return
  _filedir md
}
complete -F _dr dr

_dw()
{
   local cur prev words cword
   _init_completion || return
  _filedir
}
complete -F _dw dw
```

**Comment by pacak** [comment]
(I have something that works locally, will try to push a branch today)
