### ISSUE TITLE
Fix examples in respect to `run()`

### ISSUE THREAD

**Issue by mneumann** [pacak/bpaf#42]
When I follow the examples and derive an `Opts`, `opts().run()` complains with 

    no method named `run` found for opaque type `impl Parser<Options>` in the current scope

It must be `opts().to_options().run()`. 

Would be great to catch these things using doctests etc.

**Comment by mneumann** [comment]
Okay, tricky enough, when I use `#[bpaf(options)]` this works :)

**Comment by pacak** [comment]
Documentation kind of mentions this:
https://docs.rs/bpaf/0.5.4/bpaf/_derive_tutorial/index.html

Main motivation to skip `#[bpaf(options)]` part is to make sure examples for combinatoric and derive parts behave the same way and with combinatoric you more often need `impl Parser<T>` for individual fields so you can compose them later. Do you think this cam be improved?

**Comment by mneumann** [comment]
@pacak I think the tutorial is great! I probably just missed the "<--- this is important" :)
