### ISSUE TITLE
`Positional<>` is not exposed in help output

### ISSUE THREAD

**Issue by epage** [pacak/bpaf#43]
Its not on the [index](https://docs.rs/bpaf/latest/bpaf/) nor can you click through to it on [positional's page](https://docs.rs/bpaf/latest/bpaf/fn.positional.html)

**Comment by pacak** [comment]
Ouch, thank you for the report. It's a historical thing where Positional used to be just a parser and it made little sense to expose it, but now there's some methods there. Will add some docs
