### ISSUE TITLE
Shell completion not working in zsh

### ISSUE THREAD

**Issue by jannschu** [pacak/bpaf#46]
# Setup

I used this code:

```rust
use bpaf::Bpaf;

#[derive(Debug, Clone, Bpaf)]
#[bpaf(options)]
enum X {
    #[bpaf(command)]
    Abcdef,
}

fn main() {
    x().run();
}
```

_Cargo.toml_
```toml
bpaf = { version = "0.5.6", features = ["autocomplete", "derive"] }
```

I added this to `.zshrc`:

```zsh
#compdef myprogram
_myprogram_completion() {
    IFS=$'\n' lines=($( "${words[1]}" --bpaf-complete-rev=2 "${words[@]:1}" ))
    for line in "${(@)lines}" ; do
        IFS=$'' parts=($( echo $line ))
        cmd=()
        if [[ -n $parts[2] ]] ; then
            descr=($parts[2])
            cmd+=(-d descr)
        fi
        if [[ -n $parts[3] ]] ; then
            cmd+=(-X "${parts[3]}")
        fi
        if [[ -n $parts[4] ]] ; then
            cmd+=(-J "${parts[4]}")
        fi
        compadd ${cmd[@]} -- "$parts[1]"
    done
}
compdef _myprogram_completion myprogram;
```

This is inspired by how the Python `click` library does it. Adding `.zsh/_myprogram` did not work:

I'm using zsh 5.8.1 on macOS.

# Steps

When I run `cargo run -- --bpaf-complete-rev=2 a` it outputs

```
abcdefabcdef
```

I expected `abcdef`.

In zsh the input `myprogram a<TAB>` is completed to `myprogram abcdef$'\0'abcdef$'\0'$'\0'`.

**Comment by pacak** [comment]
Looks like some escaping gets lost, thank you for the report. 
Try using this on the 5th line.
```bash
        IFS=$'\0' parts=($( echo $line ))
```

**Comment by pacak** [comment]
Should be fixed in 5d17f22e918eb197e19f009095e8dae2003f7470, but you only need to generate the completer snippet itself, completion should work with currently released version.

**Comment by pacak** [comment]
Released 0.5.7 with the bugfix.

**Comment by jannschu** [comment]
Nice,  thanks! :)

**Comment by pacak** [comment]
Please let me know if you notice any surprising behavior.
