### ISSUE TITLE
Parsing negative values

### ISSUE THREAD

**Issue by rminderhoud** [pacak/bpaf#5]
Hello, it seems that parsing negative values is not working since bpaf detects it as a flag, minimal example running on MacOS in a zsh shell.:

```rust
    let age= long("age")
        .argument("AGE")
        .from_str::<i64>()
```

```
> test --age -1
--age requires an argument, got flag -1
```

Thanks!

**Comment by pacak** [comment]
This is expected and not unique to bpaf: [1]. For passing a value that starts with dash user needs to use either `--age=-1` or `--age -- -1` syntax, later will turn anything that follows into a word. Requiring explicit annotation helps to avoid ambiguous  situations when behavior of a whole groups of changes depending on how the first one is handled.


[1] https://stackoverflow.com/questions/37752454/passing-bash-a-value-with-leading-hyphen

**Comment by rminderhoud** [comment]
I agree, avoiding ambiguity by being explicit with a special annotation makes sense. Glad to see this was just my user error and not in fact a bug.
