### ISSUE TITLE
Suggestion: split construct into two / ability to construct! arrays

### ISSUE THREAD

**Issue by d86leader** [pacak/bpaf#70]
Currently, from reading the docs, construct can do two things:
1. Lift the constructor a-la [`<*>`](https://pursuit.purescript.org/packages/purescript-prelude/6.0.1/docs/Control.Apply#t:Apply) operator
2. Chain parsers a-la [`<|>`](https://pursuit.purescript.org/packages/purescript-control/6.0.0/docs/Control.Alt#t:Alt) operator

The second usage conflicts with the first usage to construct a slice, for example: `let s: [Opt; 3] = construct!([parser1, parser2, p3])`. Not that anyone would really write something like this, but it seems weird to me that you can't.

Maybe it's worth it to split it into `construct` and `sequence`?

**Comment by pacak** [comment]
I could change syntax to be `construct!(a | b | c)`, but constructing arrays doesn't feel like it comes up often.

When I want a structure but too lazy to give it a name - I'd parse it into a tuple: `let st: (Opt, Opt, Opt) = construct!(parser1, parser2, p3)` - you'll get more type safety when accessing fields: `st.3` is a compile time error, `s[3]` is a runtime crash. You will get an ability to access it as a slice.

A second alternative would be parsing them into a vector: `construct!([p1, p2, p3]).many()`, but behavior is slightly different.

And finally you can create an array by doing extra processing from a tuple. A bit ugly though.

Anyway, I'll keep the ticket open to collect some feedback, we'll see. With enough interest it's doable.
