### ISSUE TITLE
Question: Default/Fallback for many/some?

### ISSUE THREAD

**Issue by xitep** [pacak/bpaf#79]
Hello, first of all many thanks for this beautiful library!

I was wondering how I could achieve providing a calculated default for a `.many()` parser as demonstrated in the following test. (I also tried using `.some(..)` but that fails as well :/) Any ideas?

```rust
    #[test]
    fn default_positional() {
        use bpaf;

        let roots = bpaf::positional::<String>("ROOTS")
            .fallback_with::<_, String>(|| Ok(String::from(".")))
            .many();

        struct Roots { roots: Vec<String>, }

        let r = construct!(Roots {roots}).to_options().run_inner(Args::from(&[]));
        assert_eq!(vec![String::from(".")], r.unwrap().roots);
    }
```

**Comment by pacak** [comment]
That's a tricky one. `fallback` and `fallback_with` are triggered by "missing item" error, but neither `many` nor `some` generates them: `many` is happy with whatever you give it including nothing, `some` - throws a string. One possible solution would be using `map` or `parse`, like so:

```rust
#[test]
fn default_for_many() {
    use bpaf;

    let roots = bpaf::positional::<String>("ROOTS").many().map(|items| {
        if items.is_empty() {
            vec![String::from(".")]
        } else {
            items
        }
    });

    struct Roots {
        roots: Vec<String>,
    }

    let r = construct!(Roots { roots })
        .to_options()
        .run_inner(Args::from(&[]));
    assert_eq!(vec![String::from(".")], r.unwrap().roots);
}
```

**Comment by pacak** [comment]
I think this should go into FAQ, can you copy your question there?

**Comment by pacak** [comment]
And for paths you should be using `PathBuf`, but I'm assuming `String` is there just for simplicity.

**Comment by xitep** [comment]
* Wow, many thanks!
* I'm not sure it's a "frequently asked question", but I can add it, of course.
* Yes, the example I've posted was retrofitted for demo purposes.
* I've had an attempt at "fixing" the `fallback_with` method for the `.many()` and `.some(..)` parsers, but ultimately failed. Nevertheless, I was able to add a `pure_with` parser - equivalent to `pure` for fallible, lazy value computation - which allowed me to write this (snippet from a test):
```rust
    let user_seeds = positional::<u32>("SEED").some("at least one required");
    let last_seeds = pure_with(|| {
        // ~ trying to lookup the last used seeds from some file
        Err("oh, no!")
    });
    let default_seeds = pure(vec![1, 2]);
    let seeds = construct!([user_seeds, last_seeds, default_seeds]).to_options().run..
```
I'll submit a merge request and leave it up to you to decide whether to include it or not.

**Comment by pacak** [comment]
> By referring to "FAQ" did you actually mean [Q&A](https://github.com/pacak/bpaf/discussions/categories/q-a)?

Right, that place.

> I'll submit a merge request and leave it up to you to decide whether to include it or not.

Cool, will reply there.

**Comment by pacak** [comment]
OK, question was answered, we'll continue discussion about #81 in the pull request.
