### ISSUE TITLE
cauwugo add: `--dev` and `--build` are supposed to be mutually exclusove

### ISSUE THREAD

**Issue by epage** [pacak/bpaf#92]

**Comment by pacak** [comment]
Hmm... Any reasons? I can totally see myself adding `anyhow` as both build and dev dependencies, in fact I was thinking about doing just that to docs crate to make errors a bit more developer friendly. But yea, will make the change.

**Comment by epage** [comment]
`cargo add` adds to just one location at a time.  You also can't specify multiple packages to add to (iirc)
